### ISSUE TITLE
Error occurred in duostra Shortest_path router

### ISSUE THREAD

**Issue by arttr1521** [DVLab-NTU/qsyn#62]
As title, an error occurred while running the following dofile.
[Shortest_path.txt](https://github.com/DVLab-NTU/qsyn/files/14402500/Shortest_path.txt)

The error message:
`std::tuple<QubitIdType, QubitIdType> qsyn::device::Device::get_next_swap_cost(QubitIdType, QubitIdType): Assertion "q_source.is_adjacency(q_next)" failed.
Aborted (core dumped)`

**Comment by arttr1521** [comment]
@chinyi0523

**Comment by JoshuaLau0220** [comment]
Fixed in #109
